# setup
setup: scan
to_noisy_dataset: False
dataset: cifar10
data_path: ../data/cifar10/
pretext_path: PRN18_800ep_bs512


# Loss
criterion: scan
criterion_kwargs:
   entropy_weight: 5.0

# Weight update
update_cluster_head_only: False # Update full network in SCAN
num_heads: 1 # Only use one head

# Model
backbone: PRN18

# Dataset
train_db_name: cifar-10
val_db_name: cifar-10
num_classes: 10
num_neighbors: 20

# Transformations
augmentation_strategy: ours 
augmentation_kwargs:
   crop_size: 32
   normalize:
      mean: [0.5071, 0.4867, 0.4408]
      std: [0.2675, 0.2565, 0.2761]
   num_strong_augs: 4
   cutout_kwargs:
     n_holes: 1
     length: 16
     random: True

transformation_kwargs:
   crop_size: 32
   normalize:
      mean: [0.5071, 0.4867, 0.4408]
      std: [0.2675, 0.2565, 0.2761]

# Hyperparameters
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001
epochs: 50
batch_size: 128
num_workers: 12

# Scheduler
scheduler: constant
