# Setup
setup: moco # MoCo is used here

# Model
backbone: InceptionResNetV2
model_kwargs:
   head: mlp
   features_dim: 128

# Dataset
data_path: '../../data/data_webvision/'
train_db_name: webvision
val_db_name: webvision
num_classes: 50
temperature: 0.07

# Batch size and workers
batch_size: 256 
num_workers: 8

# Transformations
transformation_kwargs:
   crop_size: 224
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
