# setup
setup: propmix
data_path: ../../datasets/data_webvision/
train_db_name: webvision
val_db_name: webvision
dataset: webvision
to_noisy_dataset: False # already noisy
scan_path: 'pretrained_mocov2'

# Loss
criterion: scanmix
criterion_kwargs:
   entropy_weight: 5.0

# Hyperparameters
num_epochs: 100
epochs: 100
alpha: 0.5
batch_size: 32
batch_size_scan: 32
p_threshold: 0.5
T: 0.5
num_class: 50
num_classes: 50
warmup: 1
num_workers: 8
update_cluster_head_only: False
num_neighbors: 20

# Transformations
augmentation_strategy: dividemix_webv
augmentation_kwargs:
   crop_size: 227
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

scan_kwargs:
   crop_size: 227
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
   num_strong_augs: 4
   cutout_kwargs:
     n_holes: 1
     length: 75
     random: True


lr: 0.01
#optimisers
optimizer: sgd
optimizer_kwargs:
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0005

#model
backbone: InceptionResNetV2
num_heads: 2

# Scheduler
scheduler: constant