# setup
setup: propmix
data_path: '../../datasets/red_blue/mini-imagenet/'
train_db_name: mini_imagenet32_red
val_db_name: mini_imagenet32_red
dataset: mini_imagenet32_red
to_noisy_dataset: False # already noisy
noise_dir: None


# Loss
criterion: scanmix
criterion_kwargs:
   entropy_weight: 5.0

# Hyperparameters
num_epochs: 300
epochs: 300
alpha: 0.5
batch_size: 64
batch_size_scan: 128
p_threshold: 0.5
T: 0.5
num_class: 100
num_classes: 100
warmup: 1
num_workers: 8
update_cluster_head_only: False
num_neighbors: 20

# Transformations
augmentation_strategy: dividemix_red_mini_imagenet 
augmentation_kwargs:
   resize: 32
   random_resized_crop:
      size: 32
      scale: [0.08, 1.0]
   crop_size: 32
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
   num_strong_augs: 4
   cutout_kwargs:
     n_holes: 1
     length: 16
     random: True
   

scan_kwargs:
   resize: 32
   crop_size: 32
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
   num_strong_augs: 4
   cutout_kwargs:
     n_holes: 1
     length: 16
     random: True

lr: 0.02
#optimisers
optimizer: sgd
optimizer_kwargs:
  lr: 0.02
  momentum: 0.9
  weight_decay: 0.0005

#model
backbone: resnet18
num_heads: 2

# Scheduler
scheduler: constant