# setup
setup: propmix
data_path: ../../data/cifar10/cifar-10-batches-py
train_db_name: cifar-10-plc
val_db_name: cifar-10-plc
dataset: cifar10
noise_dir: ./noise/plc
plots_dir: plots
to_noisy_dataset: True
scan_path: 'pretrained_resnet34'

# Loss
criterion: scanmix
criterion_kwargs:
   entropy_weight: 5.0

# Hyperparameters
num_epochs: 300
epochs: 300
alpha: 4
batch_size: 64
batch_size_scan: 128
p_threshold: 0.5
T: 0.5
num_class: 10
num_classes: 10
warmup: 10
num_workers: 5
update_cluster_head_only: False
num_neighbors: 20

# Transformations
augmentation_strategy: dividemix 
augmentation_kwargs:
   crop_size: 32
   crop_padding: 4
   normalize:
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]
   num_strong_augs: 4
   cutout_kwargs:
     n_holes: 1
     length: 16
     random: True

lr: 0.02
#optimisers
optimizer: sgd
optimizer_kwargs:
  lr: 0.02
  momentum: 0.9
  weight_decay: 0.0005

#model
backbone: resnet34
num_heads: 2

# Scheduler
scheduler: constant