# setup
setup: scanmix
data_path: ../../datasets/ILSVRC2012_val/
train_db_name: imagenet_100
val_db_name: imagenet_100
dataset: imagenet_val
to_noisy_dataset: False # already noisy

# Loss
criterion: scanmix
criterion_kwargs:
   entropy_weight: 5.0

# Hyperparameters
num_epochs: 0
epochs: 0
alpha: 0.5
batch_size: 64
batch_size_scan: 64
p_threshold: 0.5
T: 0.5
num_class: 50
num_classes: 50
warmup: 1
num_workers: 8
update_cluster_head_only: False
num_neighbors: 20

# Transformations
augmentation_strategy: dividemix 
augmentation_kwargs:
   resize: 256
   crop_size: 227
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

scan_kwargs:
   crop_size: 227
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
   num_strong_augs: 4
   cutout_kwargs:
     n_holes: 1
     length: 75
     random: True

lr: 0.02
#optimisers
optimizer: sgd
optimizer_kwargs:
  lr: 0.02
  momentum: 0.9
  weight_decay: 0.0005

#model
backbone: InceptionResNetV2
num_heads: 2

# Scheduler
scheduler: constant